from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT
import io
from datetime import datetime

def generate_pdf_report(language, review_type, code, result):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch
    )

    # Styles
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Title"],
        fontSize=24,
        textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=10,
        alignment=TA_CENTER
    )

    subtitle_style = ParagraphStyle(
        "SubtitleStyle",
        parent=styles["Normal"],
        fontSize=12,
        textColor=colors.HexColor("#4a4a8a"),
        spaceAfter=20,
        alignment=TA_CENTER
    )

    heading_style = ParagraphStyle(
        "HeadingStyle",
        parent=styles["Heading2"],
        fontSize=14,
        textColor=colors.HexColor("#1a1a2e"),
        spaceBefore=15,
        spaceAfter=8
    )

    normal_style = ParagraphStyle(
        "NormalStyle",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#333333"),
        spaceAfter=6,
        leading=16
    )

    code_style = ParagraphStyle(
        "CodeStyle",
        parent=styles["Code"],
        fontSize=9,
        textColor=colors.HexColor("#2d2d2d"),
        backColor=colors.HexColor("#f5f5f5"),
        spaceAfter=10,
        leading=14
    )

    # Build content
    content = []

    # Title
    content.append(Paragraph("🔍 AI Code Review Report", title_style))
    content.append(Paragraph(
        f"Generated on {datetime.now().strftime('%B %d, %Y at %H:%M')}",
        subtitle_style
    ))
    content.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#4a4a8a")))
    content.append(Spacer(1, 20))

    # Report Details
    content.append(Paragraph("📋 Report Details", heading_style))
    content.append(Paragraph(f"<b>Language:</b> {language}", normal_style))
    content.append(Paragraph(f"<b>Review Type:</b> {review_type}", normal_style))
    content.append(Spacer(1, 10))

    # Code Section
    content.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cccccc")))
    content.append(Paragraph("💻 Reviewed Code", heading_style))
    
    # Split code into lines to avoid overflow
    code_lines = code[:1500] + ("..." if len(code) > 1500 else "")
    safe_code = code_lines.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    content.append(Paragraph(safe_code, code_style))
    content.append(Spacer(1, 10))

    # Review Results
    content.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cccccc")))
    content.append(Paragraph("📊 Review Results", heading_style))

    # Clean result text for PDF
    for line in result.split("\n"):
        if line.strip() == "":
            content.append(Spacer(1, 6))
        else:
            # Remove emojis that reportlab can't render
            clean_line = line.encode('ascii', 'ignore').decode('ascii').strip()
            if clean_line:
                if line.startswith("#"):
                    content.append(Paragraph(clean_line.replace("#", "").strip(), heading_style))
                else:
                    content.append(Paragraph(clean_line, normal_style))

    # Footer
    content.append(Spacer(1, 20))
    content.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#4a4a8a")))
    content.append(Paragraph("Generated by AI Code Reviewer", subtitle_style))

    # Build PDF
    doc.build(content)
    buffer.seek(0)
    return buffer